package edu.pja.pskomorowski.sri.corba;

import edu.pja.pskomorowski.sri.corba.CostumerPackage.rented_carsHelper;

/**
* _CostumerImplBase.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from RentalCar.idl
* Friday, 17 June 2022 23:01:07 o'clock CEST
*/

public abstract class _CostumerImplBase extends org.omg.CORBA.portable.ObjectImpl
                implements Costumer, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors
  public _CostumerImplBase ()
  {
  }

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("_get_fees", new java.lang.Integer (0));
    _methods.put ("_set_fees", new java.lang.Integer (1));
    _methods.put ("_get_rentedCars", new java.lang.Integer (2));
    _methods.put ("_set_rentedCars", new java.lang.Integer (3));
    _methods.put ("rentalTimes", new java.lang.Integer (4));
    _methods.put ("increaseRental", new java.lang.Integer (5));
    _methods.put ("addFees", new java.lang.Integer (6));
    _methods.put ("payOffFees", new java.lang.Integer (7));
    _methods.put ("_get_name", new java.lang.Integer (8));
    _methods.put ("_set_name", new java.lang.Integer (9));
    _methods.put ("_get_sureName", new java.lang.Integer (10));
    _methods.put ("_set_sureName", new java.lang.Integer (11));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // Costumer/_get_fees
       {
         int $result = (int)0;
         $result = this.fees ();
         out = $rh.createReply();
         out.write_long ($result);
         break;
       }

       case 1:  // Costumer/_set_fees
       {
         int newFees = in.read_long ();
         this.fees (newFees);
         out = $rh.createReply();
         break;
       }

       case 2:  // Costumer/_get_rentedCars
       {
         Car $result[] = null;
         $result = this.rentedCars ();
         out = $rh.createReply();
         rented_carsHelper.write (out, $result);
         break;
       }

       case 3:  // Costumer/_set_rentedCars
       {
         Car newRentedCars[] = rented_carsHelper.read (in);
         this.rentedCars (newRentedCars);
         out = $rh.createReply();
         break;
       }

       case 4:  // Costumer/rentalTimes
       {
         int $result = (int)0;
         $result = this.rentalTimes ();
         out = $rh.createReply();
         out.write_long ($result);
         break;
       }

       case 5:  // Costumer/increaseRental
       {
         this.increaseRental ();
         out = $rh.createReply();
         break;
       }

       case 6:  // Costumer/addFees
       {
         int newFees = in.read_long ();
         this.addFees (newFees);
         out = $rh.createReply();
         break;
       }

       case 7:  // Costumer/payOffFees
       {
         int newFees = in.read_long ();
         this.payOffFees (newFees);
         out = $rh.createReply();
         break;
       }

       case 8:  // Person/_get_name
       {
         String $result = null;
         $result = this.name ();
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 9:  // Person/_set_name
       {
         String newName = in.read_string ();
         this.name (newName);
         out = $rh.createReply();
         break;
       }

       case 10:  // Person/_get_sureName
       {
         String $result = null;
         $result = this.sureName ();
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 11:  // Person/_set_sureName
       {
         String newSureName = in.read_string ();
         this.sureName (newSureName);
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:Costumer:1.0", 
    "IDL:Person:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }


} // class _CostumerImplBase
