package edu.pja.pskomorowski.sri.corba;

/**
* Car.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from RentalCar.idl
* Friday, 17 June 2022 22:49:27 o'clock CEST
*/

public final class Car implements org.omg.CORBA.portable.IDLEntity
{
  public String name = null;
  public double cc = (double)0;
  public String vin = null;
  public int year = (int)0;

  public Car ()
  {
  } // ctor

  public Car (String _name, double _cc, String _vin, int _year)
  {
    name = _name;
    cc = _cc;
    vin = _vin;
    year = _year;
  } // ctor

} // class Car
