package edu.pja.pskomorowski.sri.corba;

/**
* CarOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from RentalCar.idl
* Friday, 17 June 2022 22:14:45 o'clock CEST
*/

public interface CarOperations 
{
  String name ();
  void name (String newName);
  double cc ();
  void cc (double newCc);
  String vin ();
  void vin (String newVin);
  int year ();
  void year (int newYear);
} // interface CarOperations
