package edu.pja.pskomorowski.sri.corba;

/**
* PersonHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from RentalCar.idl
* Friday, 17 June 2022 22:49:27 o'clock CEST
*/

abstract public class PersonHelper
{
  private static String  _id = "IDL:Person:1.0";

  public static void insert (org.omg.CORBA.Any a, Person that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static Person extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (PersonHelper.id (), "Person");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static Person read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_PersonStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, Person value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static Person narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof Person)
      return (Person)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      _PersonStub stub = new _PersonStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static Person unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof Person)
      return (Person)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      _PersonStub stub = new _PersonStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
