package edu.pja.pskomorowski.sri.corba;

/**
* RentalCar.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from RentalCar.idl
* Friday, 17 June 2022 22:49:27 o'clock CEST
*/

public interface RentalCar extends RentalCarOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface RentalCar
