package edu.pja.pskomorowski.sri.corba;

/**
* RentalCarHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from RentalCar.idl
* Friday, 17 June 2022 22:49:27 o'clock CEST
*/

abstract public class RentalCarHelper
{
  private static String  _id = "IDL:RentalCar:1.0";

  public static void insert (org.omg.CORBA.Any a, RentalCar that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static RentalCar extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (RentalCarHelper.id (), "RentalCar");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static RentalCar read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_RentalCarStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, RentalCar value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static RentalCar narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof RentalCar)
      return (RentalCar)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      _RentalCarStub stub = new _RentalCarStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static RentalCar unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof RentalCar)
      return (RentalCar)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      _RentalCarStub stub = new _RentalCarStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
