package edu.pja.pskomorowski.sri.corba;

import edu.pja.pskomorowski.sri.corba.RentalCarPackage.AlreadyRented;
import edu.pja.pskomorowski.sri.corba.RentalCarPackage.IsNotForRental;
import edu.pja.pskomorowski.sri.corba.RentalCarPackage.NotRented;

/**
* RentalCarOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from RentalCar.idl
* Friday, 17 June 2022 22:49:27 o'clock CEST
*/

public interface RentalCarOperations 
{
  int priceForDay ();
  void priceForDay (int newPriceForDay);
  boolean isForRent ();
  void isForRent (boolean newIsForRent);
  int rentedTimes ();
  void rentedTimes (int newRentedTimes);
  Car CarStruct ();
  void CarStruct (Car newCarStruct);
  void rent (Costumer cost) throws AlreadyRented, IsNotForRental;
  int priceForDays (int days);
  void unrent () throws NotRented;
  Person currRenting ();
} // interface RentalCarOperations
