package edu.pja.pskomorowski.sri.corba;

/**
* RentalCarHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from RentalCar.idl
* Friday, 17 June 2022 22:49:27 o'clock CEST
*/

public final class RentalCarHolder implements org.omg.CORBA.portable.Streamable
{
  public RentalCar value = null;

  public RentalCarHolder ()
  {
  }

  public RentalCarHolder (RentalCar initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = RentalCarHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    RentalCarHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return RentalCarHelper.type ();
  }

}
