
/**
* CostumerOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from RentalCar.idl
* Friday, 17 June 2022 23:01:07 o'clock CEST
*/

public interface CostumerOperations  extends PersonOperations
{
  int fees ();
  void fees (int newFees);
  Car[] rentedCars ();
  void rentedCars (Car[] newRentedCars);
  int rentalTimes ();
  void increaseRental ();
  void addFees (int newFees);
  void payOffFees (int newFees);
} // interface CostumerOperations
