
/**
* Costumer.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from RentalCar.idl
* Friday, 17 June 2022 23:01:07 o'clock CEST
*/

public interface Costumer extends CostumerOperations, Person, org.omg.CORBA.portable.IDLEntity 
{
} // interface Costumer
