
/**
* PersonOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from RentalCar.idl
* Friday, 17 June 2022 23:01:07 o'clock CEST
*/

public interface PersonOperations 
{
  String name ();
  void name (String newName);
  String sureName ();
  void sureName (String newSureName);
} // interface PersonOperations
