
/**
* rented_carsHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from RentalCar.idl
* Friday, 17 June 2022 23:01:07 o'clock CEST
*/

public final class rented_carsHolder implements org.omg.CORBA.portable.Streamable
{
  public Car value[] = null;

  public rented_carsHolder ()
  {
  }

  public rented_carsHolder (Car[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = rented_carsHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    rented_carsHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return rented_carsHelper.type ();
  }

}
