
/**
* RentalCarOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from RentalCar.idl
* Friday, 17 June 2022 23:01:07 o'clock CEST
*/

public interface RentalCarOperations 
{
  int priceForDay ();
  void priceForDay (int newPriceForDay);
  boolean isForRent ();
  void isForRent (boolean newIsForRent);
  int rentedTimes ();
  void rentedTimes (int newRentedTimes);
  Car CarStruct ();
  void CarStruct (Car newCarStruct);
  void rent (Costumer cost) throws RentalCarPackage.AlreadyRented, RentalCarPackage.IsNotForRental;
  int priceForDays (int days);
  void unrent () throws RentalCarPackage.NotRented;
  Person currRenting ();
} // interface RentalCarOperations
