package edu.pja.pskomorowski.sri.corba.CostumerPackage;


import edu.pja.pskomorowski.sri.corba.Car;
import edu.pja.pskomorowski.sri.corba.CarHelper;

/**
* CostumerPackage/rented_carsHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from RentalCar.idl
* Friday, 17 June 2022 22:49:27 o'clock CEST
*/

abstract public class rented_carsHelper
{
  private static String  _id = "IDL:Costumer/rented_cars:1.0";

  public static void insert (org.omg.CORBA.Any a, Car[] that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static Car[] extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = CarHelper.type ();
      __typeCode = org.omg.CORBA.ORB.init ().create_sequence_tc (0, __typeCode);
      __typeCode = org.omg.CORBA.ORB.init ().create_alias_tc (rented_carsHelper.id (), "rented_cars", __typeCode);
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static Car[] read (org.omg.CORBA.portable.InputStream istream)
  {
    Car value[] = null;
    int _len0 = istream.read_long ();
    value = new Car[_len0];
    for (int _o1 = 0;_o1 < value.length; ++_o1)
      value[_o1] = CarHelper.read (istream);
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, Car[] value)
  {
    ostream.write_long (value.length);
    for (int _i0 = 0;_i0 < value.length; ++_i0)
      CarHelper.write (ostream, value[_i0]);
  }

}
