package edu.pja.pskomorowski.sri.corba.RentalCarPackage;

/**
* RentalCarPackage/AlreadyRentedHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from RentalCar.idl
* Friday, 17 June 2022 22:49:27 o'clock CEST
*/

public final class AlreadyRentedHolder implements org.omg.CORBA.portable.Streamable
{
  public AlreadyRented value = null;

  public AlreadyRentedHolder ()
  {
  }

  public AlreadyRentedHolder (AlreadyRented initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = AlreadyRentedHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    AlreadyRentedHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return AlreadyRentedHelper.type ();
  }

}
