package edu.pja.pskomorowski.sri.corba.RentalCarPackage;


/**
* RentalCarPackage/IsNotForRental.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from RentalCar.idl
* Friday, 17 June 2022 22:49:28 o'clock CEST
*/

public final class IsNotForRental extends org.omg.CORBA.UserException
{

  public IsNotForRental ()
  {
    super(IsNotForRentalHelper.id());
  } // ctor


  public IsNotForRental (String $reason)
  {
    super(IsNotForRentalHelper.id() + "  " + $reason);
  } // ctor

} // class IsNotForRental
