package edu.pja.pskomorowski.sri.corba.RentalCarPackage;

/**
* RentalCarPackage/IsNotForRentalHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from RentalCar.idl
* Friday, 17 June 2022 22:49:28 o'clock CEST
*/

public final class IsNotForRentalHolder implements org.omg.CORBA.portable.Streamable
{
  public IsNotForRental value = null;

  public IsNotForRentalHolder ()
  {
  }

  public IsNotForRentalHolder (IsNotForRental initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = IsNotForRentalHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    IsNotForRentalHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return IsNotForRentalHelper.type ();
  }

}
