package edu.pja.pskomorowski.sri.corba.RentalCarPackage;


/**
* RentalCarPackage/NotRented.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from RentalCar.idl
* Friday, 17 June 2022 22:49:28 o'clock CEST
*/

public final class NotRented extends org.omg.CORBA.UserException
{

  public NotRented ()
  {
    super(NotRentedHelper.id());
  } // ctor


  public NotRented (String $reason)
  {
    super(NotRentedHelper.id() + "  " + $reason);
  } // ctor

} // class NotRented
