package RentalCarPackage;

/**
* RentalCarPackage/AlreadyRentedHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from RentalCar.idl
* Friday, 17 June 2022 23:01:07 o'clock CEST
*/

public final class AlreadyRentedHolder implements org.omg.CORBA.portable.Streamable
{
  public RentalCarPackage.AlreadyRented value = null;

  public AlreadyRentedHolder ()
  {
  }

  public AlreadyRentedHolder (RentalCarPackage.AlreadyRented initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = RentalCarPackage.AlreadyRentedHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    RentalCarPackage.AlreadyRentedHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return RentalCarPackage.AlreadyRentedHelper.type ();
  }

}
