/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package edu.pja.sri.lab07;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.13.0)", date = "2022-07-01")
public class CustomerList implements org.apache.thrift.TBase<CustomerList, CustomerList._Fields>, java.io.Serializable, Cloneable, Comparable<CustomerList> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("CustomerList");

  private static final org.apache.thrift.protocol.TField CUSTOMERS_FIELD_DESC = new org.apache.thrift.protocol.TField("customers", org.apache.thrift.protocol.TType.LIST, (short)1);

  private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new CustomerListStandardSchemeFactory();
  private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new CustomerListTupleSchemeFactory();

  public @org.apache.thrift.annotation.Nullable java.util.List<Customer> customers; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    CUSTOMERS((short)1, "customers");

    private static final java.util.Map<java.lang.String, _Fields> byName = new java.util.HashMap<java.lang.String, _Fields>();

    static {
      for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // CUSTOMERS
          return CUSTOMERS;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new java.lang.IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByName(java.lang.String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final java.lang.String _fieldName;

    _Fields(short thriftId, java.lang.String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public java.lang.String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.CUSTOMERS, new org.apache.thrift.meta_data.FieldMetaData("customers", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST, 
            new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRUCT            , "Customer"))));
    metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(CustomerList.class, metaDataMap);
  }

  public CustomerList() {
  }

  public CustomerList(
    java.util.List<Customer> customers)
  {
    this();
    this.customers = customers;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public CustomerList(CustomerList other) {
    if (other.isSetCustomers()) {
      java.util.List<Customer> __this__customers = new java.util.ArrayList<Customer>(other.customers.size());
      for (Customer other_element : other.customers) {
        __this__customers.add(new Customer(other_element));
      }
      this.customers = __this__customers;
    }
  }

  public CustomerList deepCopy() {
    return new CustomerList(this);
  }

  @Override
  public void clear() {
    this.customers = null;
  }

  public int getCustomersSize() {
    return (this.customers == null) ? 0 : this.customers.size();
  }

  @org.apache.thrift.annotation.Nullable
  public java.util.Iterator<Customer> getCustomersIterator() {
    return (this.customers == null) ? null : this.customers.iterator();
  }

  public void addToCustomers(Customer elem) {
    if (this.customers == null) {
      this.customers = new java.util.ArrayList<Customer>();
    }
    this.customers.add(elem);
  }

  @org.apache.thrift.annotation.Nullable
  public java.util.List<Customer> getCustomers() {
    return this.customers;
  }

  public CustomerList setCustomers(@org.apache.thrift.annotation.Nullable java.util.List<Customer> customers) {
    this.customers = customers;
    return this;
  }

  public void unsetCustomers() {
    this.customers = null;
  }

  /** Returns true if field customers is set (has been assigned a value) and false otherwise */
  public boolean isSetCustomers() {
    return this.customers != null;
  }

  public void setCustomersIsSet(boolean value) {
    if (!value) {
      this.customers = null;
    }
  }

  public void setFieldValue(_Fields field, @org.apache.thrift.annotation.Nullable java.lang.Object value) {
    switch (field) {
    case CUSTOMERS:
      if (value == null) {
        unsetCustomers();
      } else {
        setCustomers((java.util.List<Customer>)value);
      }
      break;

    }
  }

  @org.apache.thrift.annotation.Nullable
  public java.lang.Object getFieldValue(_Fields field) {
    switch (field) {
    case CUSTOMERS:
      return getCustomers();

    }
    throw new java.lang.IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new java.lang.IllegalArgumentException();
    }

    switch (field) {
    case CUSTOMERS:
      return isSetCustomers();
    }
    throw new java.lang.IllegalStateException();
  }

  @Override
  public boolean equals(java.lang.Object that) {
    if (that == null)
      return false;
    if (that instanceof CustomerList)
      return this.equals((CustomerList)that);
    return false;
  }

  public boolean equals(CustomerList that) {
    if (that == null)
      return false;
    if (this == that)
      return true;

    boolean this_present_customers = true && this.isSetCustomers();
    boolean that_present_customers = true && that.isSetCustomers();
    if (this_present_customers || that_present_customers) {
      if (!(this_present_customers && that_present_customers))
        return false;
      if (!this.customers.equals(that.customers))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    int hashCode = 1;

    hashCode = hashCode * 8191 + ((isSetCustomers()) ? 131071 : 524287);
    if (isSetCustomers())
      hashCode = hashCode * 8191 + customers.hashCode();

    return hashCode;
  }

  @Override
  public int compareTo(CustomerList other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = java.lang.Boolean.valueOf(isSetCustomers()).compareTo(other.isSetCustomers());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetCustomers()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.customers, other.customers);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  @org.apache.thrift.annotation.Nullable
  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    scheme(iprot).read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    scheme(oprot).write(oprot, this);
  }

  @Override
  public java.lang.String toString() {
    java.lang.StringBuilder sb = new java.lang.StringBuilder("CustomerList(");
    boolean first = true;

    sb.append("customers:");
    if (this.customers == null) {
      sb.append("null");
    } else {
      sb.append(this.customers);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, java.lang.ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class CustomerListStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public CustomerListStandardScheme getScheme() {
      return new CustomerListStandardScheme();
    }
  }

  private static class CustomerListStandardScheme extends org.apache.thrift.scheme.StandardScheme<CustomerList> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, CustomerList struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // CUSTOMERS
            if (schemeField.type == org.apache.thrift.protocol.TType.LIST) {
              {
                org.apache.thrift.protocol.TList _list8 = iprot.readListBegin();
                struct.customers = new java.util.ArrayList<Customer>(_list8.size);
                @org.apache.thrift.annotation.Nullable Customer _elem9;
                for (int _i10 = 0; _i10 < _list8.size; ++_i10)
                {
                  _elem9 = new Customer();
                  _elem9.read(iprot);
                  struct.customers.add(_elem9);
                }
                iprot.readListEnd();
              }
              struct.setCustomersIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, CustomerList struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.customers != null) {
        oprot.writeFieldBegin(CUSTOMERS_FIELD_DESC);
        {
          oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, struct.customers.size()));
          for (Customer _iter11 : struct.customers)
          {
            _iter11.write(oprot);
          }
          oprot.writeListEnd();
        }
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class CustomerListTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public CustomerListTupleScheme getScheme() {
      return new CustomerListTupleScheme();
    }
  }

  private static class CustomerListTupleScheme extends org.apache.thrift.scheme.TupleScheme<CustomerList> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, CustomerList struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet optionals = new java.util.BitSet();
      if (struct.isSetCustomers()) {
        optionals.set(0);
      }
      oprot.writeBitSet(optionals, 1);
      if (struct.isSetCustomers()) {
        {
          oprot.writeI32(struct.customers.size());
          for (Customer _iter12 : struct.customers)
          {
            _iter12.write(oprot);
          }
        }
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, CustomerList struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet incoming = iprot.readBitSet(1);
      if (incoming.get(0)) {
        {
          org.apache.thrift.protocol.TList _list13 = new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, iprot.readI32());
          struct.customers = new java.util.ArrayList<Customer>(_list13.size);
          @org.apache.thrift.annotation.Nullable Customer _elem14;
          for (int _i15 = 0; _i15 < _list13.size; ++_i15)
          {
            _elem14 = new Customer();
            _elem14.read(iprot);
            struct.customers.add(_elem14);
          }
        }
        struct.setCustomersIsSet(true);
      }
    }
  }

  private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
    return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
  }
}

